const sampleListings = [
    {
        image: "https://upload.wikimedia.org/wikipedia/commons/6/6d/2017_Honda_Civic_SR_VTEC_1.0_Front.jpg",
        condition: "used",
        carType: "petrol",
        registrationType: "private",
        registrationDate: "04-08-2016",
        brandModel: "Honda Civic",
        mileage: 38000,
        year: 2015,
        seat: 5,
        color: "White",
        title: "Honda Civic",
        description: "Well-maintained sedan",
        price: 19000,
        location: "Kuala Lumpur, Malaysia",
    },
    {
        image: "https://hips.hearstapps.com/hmg-prod/images/2021-toyota-camry-hybrid-xle-mmp-1-1603215410.png?crop=0.796xw:1.00xh;0.103xw,0&resize=768:*",
        condition: "used",
        carType: "petrol",
        registrationType: "private",
        registrationDate: "12-15-2017",
        brandModel: "Toyota Camry",
        mileage: 45000,
        year: 2016,
        seat: 5,
        color: "Silver",
        title: "Toyota Camry",
        description: "Reliable and spacious sedan",
        price: 22000,
        location: "Penang, Malaysia",
    },
    {
        image: "https://images.wapcar.my/file1/50ff7808ac014b4f9f1e95c752ac605e_1125x630.jpg",
        condition: "used",
        carType: "petrol",
        registrationType: "private",
        registrationDate: "08-25-2018",
        brandModel: "Nissan Almera",
        mileage: 32000,
        year: 2017,
        seat: 5,
        color: "Red",
        title: "Nissan Almera",
        description: "Compact and fuel-efficient",
        price: 15000,
        location: "Johor Bahru, Malaysia",
    },
    {
        image: "https://www.topgear.com/sites/default/files/2022/04/51951944136_a4826c854b_k.jpg",
        condition: "used",
        carType: "petrol",
        registrationType: "private",
        registrationDate: "06-10-2015",
        brandModel: "Ford Focus",
        mileage: 42000,
        year: 2014,
        seat: 5,
        color: "Blue",
        title: "Ford Focus",
        description: "Stylish and practical choice",
        price: 18000,
        location: "Kuching, Malaysia",
    },
    {
        image: "https://media.ed.edmunds-media.com/mazda/3/2023/oem/2023_mazda_3_sedan_carbon-edition_fq_oem_1_600.jpg",
        condition: "used",
        carType: "petrol",
        registrationType: "private",
        registrationDate: "11-20-2016",
        brandModel: "Mazda 3",
        mileage: 39000,
        year: 2015,
        seat: 5,
        color: "Black",
        title: "Mazda 3",
        description: "Sporty sedan with modern features",
        price: 23000,
        location: "Kota Kinabalu, Malaysia",
    },
    {
        image: "https://cdn.motor1.com/images/mgl/3WA9qY/s1/2024-hyundai-elantra.jpg",
        condition: "used",
        carType: "petrol",
        registrationType: "private",
        registrationDate: "07-14-2017",
        brandModel: "Hyundai Elantra",
        mileage: 35000,
        year: 2016,
        seat: 5,
        color: "Gray",
        title: "Hyundai Elantra",
        description: "Reliable and comfortable sedan",
        price: 17000,
        location: "Terengganu, Malaysia",
    },
    {
        image: "https://media.ed.edmunds-media.com/volkswagen/jetta/2022/oem/2022_volkswagen_jetta_sedan_se_fq_oem_1_1600.jpg",
        condition: "used",
        carType: "petrol",
        registrationType: "private",
        registrationDate: "05-05-2014",
        brandModel: "Volkswagen Jetta",
        mileage: 48000,
        year: 2013,
        seat: 5,
        color: "White",
        title: "Volkswagen Jetta",
        description: "European elegance with spacious interior",
        price: 25000,
        location: "Selangor, Malaysia",
    },
    {
        image: "https://paultan.org/image/2018/10/Kia-2018-All-New-Optima-GT_Ext-1.jpg",
        condition: "used",
        carType: "petrol",
        registrationType: "private",
        registrationDate: "02-28-2019",
        brandModel: "Kia Optima",
        mileage: 28000,
        year: 2017,
        seat: 5,
        color: "Blue",
        title: "Kia Optima",
        description: "Comfortable sedan with low mileage",
        price: 19000,
        location: "Sabah, Malaysia",
    },
    {
        image: "https://www.mekanika.com.my/wp-content/uploads/2022/01/SUBARU-WRX-STI-07-.jpg",
        condition: "used",
        carType: "petrol",
        registrationType: "private",
        registrationDate: "09-10-2018",
        brandModel: "Subaru Impreza",
        mileage: 31000,
        year: 2017,
        seat: 5,
        color: "Silver",
        title: "Subaru Impreza",
        description: "Sporty and reliable choice",
        price: 21000,
        location: "Perak, Malaysia",
    },
    {
        image: "https://media.ed.edmunds-media.com/chevrolet/cruze/2013/oem/2013_chevrolet_cruze_sedan_2lt_fq_oem_1_1600.jpg",
        condition: "used",
        carType: "petrol",
        registrationType: "private",
        registrationDate: "03-22-2017",
        brandModel: "Chevrolet Cruze",
        mileage: 33000,
        year: 2016,
        seat: 5,
        color: "Red",
        title: "Chevrolet Cruze",
        description: "Compact sedan with modern features",
        price: 16000,
        location: "Pahang, Malaysia",
    },
    {
        image: "https://paultan.org/image/2019/10/2019_Toyota_Corolla_Altis_1.8_G_Malaysia_Ext-2.jpg",
        condition: "used",
        carType: "petrol",
        registrationType: "private",
        registrationDate: "10-18-2015",
        brandModel: "Toyota Corolla Altis",
        mileage: 40000,
        year: 2014,
        seat: 5,
        color: "White",
        title: "Toyota Corolla Altis",
        description: "Reliable sedan with low mileage",
        price: 19000,
        location: "Kuala Lumpur, Malaysia",
    },
    {
        image: "https://cdn.arstechnica.net/wp-content/uploads/2018/06/Honda-Accord-Sport-3-800x600.jpg",
        condition: "used",
        carType: "petrol",
        registrationType: "private",
        registrationDate: "07-27-2016",
        brandModel: "Honda Accord",
        mileage: 36000,
        year: 2015,
        seat: 5,
        color: "Black",
        title: "Honda Accord",
        description: "Luxurious sedan with spacious cabin",
        price: 25000,
        location: "Penang, Malaysia",
    },
    {
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/2008-Mitsubishi-Lancer.jpg/1200px-2008-Mitsubishi-Lancer.jpg",
        condition: "used",
        carType: "petrol",
        registrationType: "private",
        registrationDate: "04-14-2019",
        brandModel: "Mitsubishi Lancer",
        mileage: 27000,
        year: 2018,
        seat: 5,
        color: "Gray",
        title: "Mitsubishi Lancer",
        description: "Reliable sedan with sleek design",
        price: 22000,
        location: "Johor Bahru, Malaysia",
    },
    {
        image: "https://upload.wikimedia.org/wikipedia/commons/a/a7/Ford_Fiesta_ST-Line_%28VII%2C_Facelift%29_%E2%80%93_f_30012023.jpg",
        condition: "used",
        carType: "petrol",
        registrationType: "private",
        registrationDate: "12-02-2017",
        brandModel: "Ford Fiesta",
        mileage: 30000,
        year: 2016,
        seat: 5,
        color: "Blue",
        title: "Ford Fiesta",
        description: "Compact and fuel-efficient hatchback",
        price: 15000,
        location:"Cyberjaya,Selangor",
    }
]

module.exports = {data: sampleListings};