const sampleListings = [
    {
        image: [{
            url: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            filename: "FYP Project",
        }],
        condition: "used",
        carType: "petrol",
        registrationType: "private",
        registrationDate: "04-08-2016",
        brandModel: "Honda Civic",
        mileage: 38000,
        year: 2015,
        seat: 5,
        color: "White",
        title: "Honda Civic",
        description: "Well-maintained sedan",
        price: 19000,
        location: "Kuala Lumpur, Malaysia",
    },
    {
        image: [{
            url: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            filename: "FYP Project",
        }],
        condition: "used",
        carType: "petrol",
        registrationType: "private",
        registrationDate: "12-15-2017",
        brandModel: "Toyota Camry",
        mileage: 45000,
        year: 2016,
        seat: 5,
        color: "Silver",
        title: "Toyota Camry",
        description: "Reliable and spacious sedan",
        price: 22000,
        location: "Penang, Malaysia",
    },
    {
        image: [{
            url: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            filename: "FYP Project",
        }],

        condition: "used",
        carType: "petrol",
        registrationType: "private",
        registrationDate: "08-25-2018",
        brandModel: "Nissan Almera",
        mileage: 32000,
        year: 2017,
        seat: 5,
        color: "Red",
        title: "Nissan Almera",
        description: "Compact and fuel-efficient",
        price: 15000,
        location: "Johor Bahru, Malaysia",
    },
    {
        image: [{
            url: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            filename: "FYP Project",
        }],
        condition: "used",
        carType: "petrol",
        registrationType: "private",
        registrationDate: "06-10-2015",
        brandModel: "Ford Focus",
        mileage: 42000,
        year: 2014,
        seat: 5,
        color: "Blue",
        title: "Ford Focus",
        description: "Stylish and practical choice",
        price: 18000,
        location: "Kuching, Malaysia",
    },
    {
        image: [{
            url: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            filename: "FYP Project",
        }],

        condition: "used",
        carType: "petrol",
        registrationType: "private",
        registrationDate: "11-20-2016",
        brandModel: "Mazda 3",
        mileage: 39000,
        year: 2015,
        seat: 5,
        color: "Black",
        title: "Mazda 3",
        description: "Sporty sedan with modern features",
        price: 23000,
        location: "Kota Kinabalu, Malaysia",
    },
    {
        image: [{
            url: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            filename: "FYP Project",
        }],
        condition: "used",
        carType: "petrol",
        registrationType: "private",
        registrationDate: "07-14-2017",
        brandModel: "Hyundai Elantra",
        mileage: 35000,
        year: 2016,
        seat: 5,
        color: "Gray",
        title: "Hyundai Elantra",
        description: "Reliable and comfortable sedan",
        price: 17000,
        location: "Terengganu, Malaysia",
    },
    {
        image: [{
            url: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            filename: "FYP Project",
        }],

        condition: "used",
        carType: "petrol",
        registrationType: "private",
        registrationDate: "05-05-2014",
        brandModel: "Volkswagen Jetta",
        mileage: 48000,
        year: 2013,
        seat: 5,
        color: "White",
        title: "Volkswagen Jetta",
        description: "European elegance with spacious interior",
        price: 25000,
        location: "Selangor, Malaysia",
    },
    {
        image: [{
            url: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            filename: "FYP Project",
        }],
        condition: "used",
        carType: "petrol",
        registrationType: "private",
        registrationDate: "02-28-2019",
        brandModel: "Kia Optima",
        mileage: 28000,
        year: 2017,
        seat: 5,
        color: "Blue",
        title: "Kia Optima",
        description: "Comfortable sedan with low mileage",
        price: 19000,
        location: "Sabah, Malaysia",
    },
    {
        image: [{
            url: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            filename: "FYP Project",
        }],
        condition: "used",
        carType: "petrol",
        registrationType: "private",
        registrationDate: "09-10-2018",
        brandModel: "Subaru Impreza",
        mileage: 31000,
        year: 2017,
        seat: 5,
        color: "Silver",
        title: "Subaru Impreza",
        description: "Sporty and reliable choice",
        price: 21000,
        location: "Perak, Malaysia",
        status: "Approved"
    },
    {
        image: [{
            url: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            filename: "FYP Project",
        }],
        condition: "used",
        carType: "petrol",
        registrationType: "private",
        registrationDate: "03-22-2017",
        brandModel: "Chevrolet Cruze",
        mileage: 33000,
        year: 2016,
        seat: 5,
        color: "Red",
        title: "Chevrolet Cruze",
        description: "Compact sedan with modern features",
        price: 16000,
        location: "Pahang, Malaysia",
        status: "Approved"
    },
    {
        image: [{
            url: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            filename: "FYP Project",
        }],
        condition: "used",
        carType: "petrol",
        registrationType: "private",
        registrationDate: "10-18-2015",
        brandModel: "Toyota Corolla Altis",
        mileage: 40000,
        year: 2014,
        seat: 5,
        color: "White",
        title: "Toyota Corolla Altis",
        description: "Reliable sedan with low mileage",
        price: 19000,
        location: "Kuala Lumpur, Malaysia",
        status: "Approved"
    },
    {
        image: [{
            url: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            filename: "FYP Project",
        }],

        condition: "used",
        carType: "petrol",
        registrationType: "private",
        registrationDate: "07-27-2016",
        brandModel: "Honda Accord",
        mileage: 36000,
        year: 2015,
        seat: 5,
        color: "Black",
        title: "Honda Accord",
        description: "Luxurious sedan with spacious cabin",
        price: 25000,
        location: "Penang, Malaysia",
        status: "Disapproved"
    },
    {
        image: [{
            url: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            filename: "FYP Project",
        }],

        condition: "used",
        carType: "petrol",
        registrationType: "private",
        registrationDate: "04-14-2019",
        brandModel: "Mitsubishi Lancer",
        mileage: 27000,
        year: 2018,
        seat: 5,
        color: "Gray",
        title: "Mitsubishi Lancer",
        description: "Reliable sedan with sleek design",
        price: 22000,
        location: "Johor Bahru, Malaysia",
        status: "Disapproved"
    },
    {
        image: [{
            url: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            filename: "FYP Project",
        }],

        condition: "used",
        carType: "petrol",
        registrationType: "private",
        registrationDate: "12-02-2017",
        brandModel: "Ford Fiesta",
        mileage: 30000,
        year: 2016,
        seat: 5,
        color: "Blue",
        title: "Ford Fiesta",
        description: "Compact and fuel-efficient hatchback",
        price: 15000,
        location: "Cyberjaya,Selangor",
        status: "Disapproved"
    }
]

module.exports = { data: sampleListings };